/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import dto.Alumno;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM_202
 */
public class FormularioMatricula extends javax.swing.JDialog {
    
    private Alumno alumnoResultante;
    
    public Alumno getAlumno(){
        return alumnoResultante;
    }
    
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioMatricula.class.getName());

    /**
     * Creates new form FormularioMatricula
     */
    public FormularioMatricula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         jListAsignaturasDAM1.setVisible(false);
        jListAsignaturasDAM2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxDAM1 = new javax.swing.JCheckBox();
        jCheckBoxDAM2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButtonTarde = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListAsignaturasDAM1 = new javax.swing.JList<>();
        jButtonRegistro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAsignaturasDAM2 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(20, 33, 61));
        jLabel6.setText("Formulario de registro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 33, 61));
        jLabel2.setText("DNI");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 33, 61));
        jLabel1.setText("Nombre ");

        jTextFieldDNI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldDNI.setForeground(new java.awt.Color(20, 33, 61));

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(20, 33, 61));
        jTextFieldNombre.addActionListener(this::jTextFieldNombreActionPerformed);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 33, 61));
        jLabel3.setText("Curso ");

        jCheckBoxDAM1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxDAM1.setText("1º DAM");
        jCheckBoxDAM1.addActionListener(this::jCheckBoxDAM1ActionPerformed);

        jCheckBoxDAM2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxDAM2.setForeground(new java.awt.Color(20, 33, 61));
        jCheckBoxDAM2.setText("2º DAM");
        jCheckBoxDAM2.addActionListener(this::jCheckBoxDAM2ActionPerformed);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(20, 33, 61));
        jLabel4.setText("Turno ");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(20, 33, 61));
        jRadioButton1.setText("Diurno");

        jRadioButtonTarde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButtonTarde.setForeground(new java.awt.Color(20, 33, 61));
        jRadioButtonTarde.setText("Tarde");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(20, 33, 61));
        jLabel5.setText("Asignaturas");

        jListAsignaturasDAM1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListAsignaturasDAM1.setForeground(new java.awt.Color(20, 33, 61));
        jListAsignaturasDAM1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1 Lenguaje de marcas", "1 Entornos de Desarrollo", "1 Sistemas Informaticos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAsignaturasDAM1.setVisibleRowCount(4);
        jScrollPane3.setViewportView(jListAsignaturasDAM1);

        jButtonRegistro.setBackground(new java.awt.Color(252, 163, 17));
        jButtonRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegistro.setForeground(new java.awt.Color(20, 33, 61));
        jButtonRegistro.setText("Registro");
        jButtonRegistro.addActionListener(this::jButtonRegistroActionPerformed);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(20, 33, 61));
        jLabel7.setText("Apellido");

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldApellido.setForeground(new java.awt.Color(20, 33, 61));
        jTextFieldApellido.addActionListener(this::jTextFieldApellidoActionPerformed);

        jListAsignaturasDAM2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jListAsignaturasDAM2.setForeground(new java.awt.Color(20, 33, 61));
        jListAsignaturasDAM2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "2 Interfaz Graficas", "2 Programacion Multimedia ", "2 Sistemas de Gestion Empresarial", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListAsignaturasDAM2.setVisibleRowCount(4);
        jScrollPane1.setViewportView(jListAsignaturasDAM2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNombre)
                                        .addComponent(jTextFieldApellido)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButtonTarde))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jCheckBoxDAM1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jCheckBoxDAM2)))
                                    .addGap(6, 6, 6))))))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButtonRegistro)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxDAM1)
                                .addComponent(jCheckBoxDAM2)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButtonTarde))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonRegistro)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistroActionPerformed
        // TODO add your handling code here:
        String dni=jTextFieldDNI.getText();
        String nombre=jTextFieldNombre.getText();
        String apellido=jTextFieldApellido.getText();
        
        String curso=null;
        if (jCheckBoxDAM1.isSelected() && jCheckBoxDAM2.isSelected()) {
            curso = "1º DAM y 2º DAM";
        } else if (jCheckBoxDAM1.isSelected()) {
            curso = "1º DAM";
        } else if (jCheckBoxDAM2.isSelected()) {
            curso = "2º DAM";
        } else {
            curso = "No seleccionado";
        }
        
        String turno= null;
        if(jRadioButton1.isSelected()){
            turno="Diurno";
        }else if (jRadioButtonTarde.isSelected()){
            turno="Tarde";
        }else {
            turno="No seleccionado";
        }
        
        List<String> asignaturas = new ArrayList<>();
        if (jCheckBoxDAM1.isSelected()) {
            asignaturas.addAll(jListAsignaturasDAM1.getSelectedValuesList());
        }
        if (jCheckBoxDAM2.isSelected()) {
            asignaturas.addAll(jListAsignaturasDAM2.getSelectedValuesList());
        }
        
         if (dni.isEmpty() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "El DNI y el Nombre son obligatorios.",
                "Error de validación",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
         
         alumnoResultante = new Alumno(nombre, apellido, dni, curso, turno, asignaturas);
         
         JOptionPane.showMessageDialog(this,
            "¡Alumno matriculado con éxito!\n\n" + alumnoResultante.toString(),
            "Matrícula Completada",
            JOptionPane.INFORMATION_MESSAGE);
         
           dispose();

          
    }//GEN-LAST:event_jButtonRegistroActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jCheckBoxDAM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDAM1ActionPerformed
        // TODO add your handling code here:
         jListAsignaturasDAM1.setVisible(jCheckBoxDAM1.isSelected());
    }//GEN-LAST:event_jCheckBoxDAM1ActionPerformed

    private void jCheckBoxDAM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDAM2ActionPerformed
        // TODO add your handling code here:
         jListAsignaturasDAM2.setVisible(jCheckBoxDAM2.isSelected());
    }//GEN-LAST:event_jCheckBoxDAM2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormularioMatricula dialog = new FormularioMatricula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JCheckBox jCheckBoxDAM1;
    private javax.swing.JCheckBox jCheckBoxDAM2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jListAsignaturasDAM1;
    private javax.swing.JList<String> jListAsignaturasDAM2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonTarde;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
