/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacion4;

/**
 *
 * @author DAM_202
 */
public class Actividad4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Actividad4.class.getName());

    /**
     * Creates new form act3
     */
    public Actividad4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        sldVol = new javax.swing.JSlider();
        lblVol = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBackground(new java.awt.Color(0, 53, 102));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        sldVol.setForeground(new java.awt.Color(255, 214, 10));
        sldVol.setMajorTickSpacing(5);
        sldVol.setMinorTickSpacing(5);
        sldVol.setSnapToTicks(true);
        sldVol.addChangeListener(this::sldVolStateChanged);
        jPanel2.add(sldVol, new java.awt.GridBagConstraints());

        lblVol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVol.setForeground(new java.awt.Color(255, 214, 10));
        lblVol.setText("50%");
        lblVol.setToolTipText("");
        lblVol.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        lblVol.setPreferredSize(new java.awt.Dimension(90, 20));
        jPanel2.add(lblVol, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 53, 102));
        jPanel3.setForeground(new java.awt.Color(255, 195, 0));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(255, 195, 0));
        lblEstado.setText("Nivel Medio");
        jPanel3.add(lblEstado);

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sldVolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVolStateChanged
       int volumen = (int) (Math.round((double) sldVol.getValue() / 5)) * 5;
       
       lblVol.setText(String.valueOf(volumen) + "%");
       
       if (volumen <= 30) lblEstado.setText("Nivel Bajo");
       else if (volumen <= 70) lblEstado.setText("Nivel Medio");
       else lblEstado.setText("Nivel Alto");
    }//GEN-LAST:event_sldVolStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Actividad4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblVol;
    private javax.swing.JSlider sldVol;
    // End of variables declaration//GEN-END:variables
}
