/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Actividades1y2;

import javax.swing.JOptionPane;

/**
 *
 * @author DAM_202
 */
public class Acitividad1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Acitividad1.class.getName());

    /**
     * Creates new form Acitividad1
     */
    public Acitividad1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel_escibreNombre = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField_ingresaTextoNombre = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jButton_saludar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new java.awt.GridLayout(3, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel_escibreNombre.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel_escibreNombre.setText("Escribe Tu Nombre ");
        jPanel7.add(jLabel_escibreNombre, new java.awt.GridBagConstraints());

        jPanel6.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField_ingresaTextoNombre.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel8.add(jTextField_ingresaTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 350, 50));

        jPanel6.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jButton_saludar.setBackground(new java.awt.Color(118, 144, 163));
        jButton_saludar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton_saludar.setForeground(new java.awt.Color(242, 242, 242));
        jButton_saludar.setText("¡¡ Saludo !!");
        jButton_saludar.addActionListener(this::jButton_saludarActionPerformed);
        jPanel9.add(jButton_saludar, new java.awt.GridBagConstraints());

        jPanel6.add(jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saludarActionPerformed
        String nombre =jTextField_ingresaTextoNombre.getText();
        
        if (!nombre.trim().isEmpty()){
            JOptionPane.showMessageDialog(
                    this,                           
            "Hola " + nombre ,      
            "Saludo Personalizado",         
            JOptionPane.INFORMATION_MESSAGE
            );
                    
        }else {
            JOptionPane.showMessageDialog(this, "Porfavor introduce un nombre para saludar", "campo vacio", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton_saludarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Acitividad1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_saludar;
    private javax.swing.JLabel jLabel_escibreNombre;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField_ingresaTextoNombre;
    // End of variables declaration//GEN-END:variables
}
