/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Actividades1y2;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author DAM_202
 */
public class Actividad2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Actividad2.class.getName());

    /**
     * Creates new form Actividad1
     */
    public Actividad2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnIMC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Indice de Masa Corporal");

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBackground(new java.awt.Color(238, 249, 198));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Altura(metros)");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        txtAltura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtAltura.setPreferredSize(new java.awt.Dimension(65, 22));
        jPanel2.add(txtAltura, new java.awt.GridBagConstraints());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Peso(kg)");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel2.add(jLabel2, new java.awt.GridBagConstraints());

        txtPeso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtPeso.setPreferredSize(new java.awt.Dimension(65, 22));
        jPanel2.add(txtPeso, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(238, 249, 198));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnIMC.setBackground(new java.awt.Color(51, 102, 255));
        btnIMC.setForeground(new java.awt.Color(242, 242, 242));
        btnIMC.setText("CalcularIMC");
        btnIMC.addActionListener(this::btnIMCActionPerformed);
        jPanel3.add(btnIMC, new java.awt.GridBagConstraints());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("IMC");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel3.add(jLabel3, new java.awt.GridBagConstraints());

        txtIMC.setEditable(false);
        txtIMC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtIMC.setPreferredSize(new java.awt.Dimension(65, 22));
        jPanel3.add(txtIMC, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIMCActionPerformed
       double altura = Double.parseDouble(txtAltura.getText());
       double peso = Double.parseDouble(txtPeso.getText());
       
       double IMC = peso / Math.pow(altura,2);
       
       BigDecimal bd = BigDecimal.valueOf(IMC);
       bd = bd.setScale(2, RoundingMode.HALF_UP);
       
       IMC = bd.doubleValue();
       
       
       txtIMC.setText(String.valueOf(IMC));
       
    }//GEN-LAST:event_btnIMCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Actividad2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIMC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
