/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import dto.Producto;
import java.util.List;

/**
 *
 * @author DAM_204
 */
public class Bebidas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bebidas.class.getName());
    
      private List<Producto> listaProductos;
    private Main mainRef;
    private Producto productoSeleccionado;
    /**
     * Creates new form Bebidas
     */
  public Bebidas(java.awt.Frame parent, boolean modal, List<Producto> productos, Main main) {
        super(parent, modal);
        this.listaProductos = productos;
        this.mainRef = main; // ⬅️ Guardamos la referencia
        initComponents();
    }

  private void añadirSinCerrar(String nombreBuscado) {
        for (Producto p : listaProductos) {
            if (p.getNombre().equalsIgnoreCase(nombreBuscado)) {
                if (mainRef != null) {
                    mainRef.añadirProductoATabla(p, 1); // Añade directamente
                }
                break;
            }
        }
        // NO llamamos a dispose() → la ventana sigue abierta
    }
   
   
   
   private void seleccionarProducto(String nombreBuscado) {
        for (Producto p : listaProductos) {
            if (p.getNombre().equalsIgnoreCase(nombreBuscado)) {
                this.productoSeleccionado = p;
                break;
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnZumoDeNaranja = new javax.swing.JButton();
        btnTeHelado = new javax.swing.JButton();
        btnJugoNatural = new javax.swing.JButton();
        btnAgua = new javax.swing.JButton();
        btnVino = new javax.swing.JButton();
        btnCerveza = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelEmpresa1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCapucchino = new javax.swing.JButton();
        btnChocoloate = new javax.swing.JButton();
        btnExpresso = new javax.swing.JButton();
        btnFrappe = new javax.swing.JButton();
        btnMachiatto = new javax.swing.JButton();
        btnTeCaliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 800));

        jPanel2.setPreferredSize(new java.awt.Dimension(527, 100));

        jLabelEmpresa.setBackground(new java.awt.Color(142, 202, 230));
        jLabelEmpresa.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(2, 48, 71));
        jLabelEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpresa.setText("Bebidas Frias ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.setLayout(new java.awt.GridLayout(2, 4, 30, 30));

        btnZumoDeNaranja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasFrias/Zumo.png"))); // NOI18N
        btnZumoDeNaranja.setBorder(null);
        btnZumoDeNaranja.addActionListener(this::btnZumoDeNaranjaActionPerformed);
        jPanel3.add(btnZumoDeNaranja);

        btnTeHelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasFrias/te-helado (2).png"))); // NOI18N
        btnTeHelado.setBorder(null);
        btnTeHelado.addActionListener(this::btnTeHeladoActionPerformed);
        jPanel3.add(btnTeHelado);

        btnJugoNatural.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasFrias/jugobotella.png"))); // NOI18N
        btnJugoNatural.setBorder(null);
        btnJugoNatural.addActionListener(this::btnJugoNaturalActionPerformed);
        jPanel3.add(btnJugoNatural);

        btnAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasFrias/botella-de-agua.png"))); // NOI18N
        btnAgua.setBorder(null);
        btnAgua.addActionListener(this::btnAguaActionPerformed);
        jPanel3.add(btnAgua);

        btnVino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasFrias/copa-de-vino.png"))); // NOI18N
        btnVino.setBorder(null);
        btnVino.addActionListener(this::btnVinoActionPerformed);
        jPanel3.add(btnVino);

        btnCerveza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasFrias/cerveza.png"))); // NOI18N
        btnCerveza.setBorder(null);
        btnCerveza.addActionListener(this::btnCervezaActionPerformed);
        jPanel3.add(btnCerveza);

        jPanel4.setPreferredSize(new java.awt.Dimension(527, 100));

        jLabelEmpresa1.setBackground(new java.awt.Color(142, 202, 230));
        jLabelEmpresa1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabelEmpresa1.setForeground(new java.awt.Color(2, 48, 71));
        jLabelEmpresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpresa1.setText("Bebidas Calientes");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 231, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel6.setLayout(new java.awt.GridLayout(2, 4, 30, 30));

        btnCapucchino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasCalientes/capuchino.png"))); // NOI18N
        btnCapucchino.setBorder(null);
        btnCapucchino.addActionListener(this::btnCapucchinoActionPerformed);
        jPanel6.add(btnCapucchino);

        btnChocoloate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasCalientes/chocolate-caliente.png"))); // NOI18N
        btnChocoloate.setBorder(null);
        btnChocoloate.addActionListener(this::btnChocoloateActionPerformed);
        jPanel6.add(btnChocoloate);

        btnExpresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasCalientes/expresso.png"))); // NOI18N
        btnExpresso.setBorder(null);
        btnExpresso.addActionListener(this::btnExpressoActionPerformed);
        jPanel6.add(btnExpresso);

        btnFrappe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasCalientes/frappe2.png"))); // NOI18N
        btnFrappe.setBorder(null);
        btnFrappe.addActionListener(this::btnFrappeActionPerformed);
        jPanel6.add(btnFrappe);

        btnMachiatto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasCalientes/macchiato.png"))); // NOI18N
        btnMachiatto.setBorder(null);
        btnMachiatto.addActionListener(this::btnMachiattoActionPerformed);
        jPanel6.add(btnMachiatto);

        btnTeCaliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebidasCalientes/te-verde.png"))); // NOI18N
        btnTeCaliente.setBorder(null);
        btnTeCaliente.addActionListener(this::btnTeCalienteActionPerformed);
        jPanel6.add(btnTeCaliente);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel5.add(btnVolver);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnZumoDeNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZumoDeNaranjaActionPerformed
        seleccionarProducto("Zumo de naranja");
    }//GEN-LAST:event_btnZumoDeNaranjaActionPerformed

    private void btnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguaActionPerformed
        seleccionarProducto("Agua");
    }//GEN-LAST:event_btnAguaActionPerformed

    private void btnCervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCervezaActionPerformed
        seleccionarProducto("Cerveza");
    }//GEN-LAST:event_btnCervezaActionPerformed

    private void btnVinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVinoActionPerformed
        seleccionarProducto("Vino");
    }//GEN-LAST:event_btnVinoActionPerformed

    private void btnJugoNaturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugoNaturalActionPerformed
        seleccionarProducto("Jugo natural");
    }//GEN-LAST:event_btnJugoNaturalActionPerformed

    private void btnTeHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeHeladoActionPerformed
        seleccionarProducto("Te helado");
    }//GEN-LAST:event_btnTeHeladoActionPerformed

    private void btnChocoloateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocoloateActionPerformed
        seleccionarProducto("Chocolate");
    }//GEN-LAST:event_btnChocoloateActionPerformed

    private void btnCapucchinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapucchinoActionPerformed
        seleccionarProducto("Capucchino");
    }//GEN-LAST:event_btnCapucchinoActionPerformed

    private void btnExpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpressoActionPerformed
         seleccionarProducto("Expresso");
    }//GEN-LAST:event_btnExpressoActionPerformed

    private void btnFrappeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrappeActionPerformed
        seleccionarProducto("Frappe");
    }//GEN-LAST:event_btnFrappeActionPerformed

    private void btnMachiattoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMachiattoActionPerformed
        seleccionarProducto("Cafe con leche");
    }//GEN-LAST:event_btnMachiattoActionPerformed

    private void btnTeCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeCalienteActionPerformed
        seleccionarProducto("Te");
    }//GEN-LAST:event_btnTeCalienteActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         this.productoSeleccionado = null; 
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgua;
    private javax.swing.JButton btnCapucchino;
    private javax.swing.JButton btnCerveza;
    private javax.swing.JButton btnChocoloate;
    private javax.swing.JButton btnExpresso;
    private javax.swing.JButton btnFrappe;
    private javax.swing.JButton btnJugoNatural;
    private javax.swing.JButton btnMachiatto;
    private javax.swing.JButton btnTeCaliente;
    private javax.swing.JButton btnTeHelado;
    private javax.swing.JButton btnVino;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnZumoDeNaranja;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelEmpresa1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
