/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import dto.Producto;
import java.util.List;

/**
 *
 * @author DAM_204
 */
public class Comidas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Comidas.class.getName());

    
    private Producto productoSeleccionado;
    private List<Producto> listaProductos;

    public Comidas(java.awt.Frame parent, boolean modal, List<Producto> productos) {
        super(parent, modal);
        this.listaProductos = productos;
        initComponents();
    }

    public Producto getProductoSeleccionado() {
        return productoSeleccionado;
    }

    private void seleccionarProducto(String nombreBuscado) {
        for (Producto p : listaProductos) {
            if (p.getNombre().equalsIgnoreCase(nombreBuscado)) {
                this.productoSeleccionado = p;
                break;
            }
        }
        dispose();
    }

    /**
     * Creates new form Bebidas
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAlitas = new javax.swing.JButton();
        btnAnillosDeCalamar = new javax.swing.JButton();
        btnCroquetas = new javax.swing.JButton();
        btnChorizo = new javax.swing.JButton();
        btnTacos = new javax.swing.JButton();
        btnPapasFritas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelEmpresa1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnHamburguesa = new javax.swing.JButton();
        btnPerroCaliente = new javax.swing.JButton();
        btnBocadilloCalamar = new javax.swing.JButton();
        btnSandwich = new javax.swing.JButton();
        btnTortillaDePatata = new javax.swing.JButton();
        btnWrap = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 800));

        jPanel2.setPreferredSize(new java.awt.Dimension(527, 100));

        jLabelEmpresa.setBackground(new java.awt.Color(142, 202, 230));
        jLabelEmpresa.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(2, 48, 71));
        jLabelEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpresa.setText("Para Picar / entrantes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.setLayout(new java.awt.GridLayout(2, 4, 30, 30));

        btnAlitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comidasPicar/alitas-de-pollo.png"))); // NOI18N
        btnAlitas.setBorder(null);
        btnAlitas.addActionListener(this::btnAlitasActionPerformed);
        jPanel3.add(btnAlitas);

        btnAnillosDeCalamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comidasPicar/aros-de-cebolla.png"))); // NOI18N
        btnAnillosDeCalamar.setBorder(null);
        btnAnillosDeCalamar.addActionListener(this::btnAnillosDeCalamarActionPerformed);
        jPanel3.add(btnAnillosDeCalamar);

        btnCroquetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comidasPicar/croquetas.png"))); // NOI18N
        btnCroquetas.setBorder(null);
        btnCroquetas.addActionListener(this::btnCroquetasActionPerformed);
        jPanel3.add(btnCroquetas);

        btnChorizo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comidasPicar/embutido.png"))); // NOI18N
        btnChorizo.setBorder(null);
        btnChorizo.addActionListener(this::btnChorizoActionPerformed);
        jPanel3.add(btnChorizo);

        btnTacos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comidasPicar/nachos (1).png"))); // NOI18N
        btnTacos.setBorder(null);
        btnTacos.addActionListener(this::btnTacosActionPerformed);
        jPanel3.add(btnTacos);

        btnPapasFritas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comidasPicar/papas-fritas.png"))); // NOI18N
        btnPapasFritas.setBorder(null);
        btnPapasFritas.addActionListener(this::btnPapasFritasActionPerformed);
        jPanel3.add(btnPapasFritas);

        jPanel4.setPreferredSize(new java.awt.Dimension(527, 100));

        jLabelEmpresa1.setBackground(new java.awt.Color(142, 202, 230));
        jLabelEmpresa1.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabelEmpresa1.setForeground(new java.awt.Color(2, 48, 71));
        jLabelEmpresa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpresa1.setText("Platos Principales ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabelEmpresa1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel6.setLayout(new java.awt.GridLayout(2, 4, 30, 30));

        btnHamburguesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComidasPrincipales/bollo-de-hamburguesa.png"))); // NOI18N
        btnHamburguesa.setBorder(null);
        btnHamburguesa.addActionListener(this::btnHamburguesaActionPerformed);
        jPanel6.add(btnHamburguesa);

        btnPerroCaliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComidasPrincipales/perritos-calientes.png"))); // NOI18N
        btnPerroCaliente.setBorder(null);
        btnPerroCaliente.addActionListener(this::btnPerroCalienteActionPerformed);
        jPanel6.add(btnPerroCaliente);

        btnBocadilloCalamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComidasPrincipales/sandwich-de-calamares.png"))); // NOI18N
        btnBocadilloCalamar.setBorder(null);
        btnBocadilloCalamar.addActionListener(this::btnBocadilloCalamarActionPerformed);
        jPanel6.add(btnBocadilloCalamar);

        btnSandwich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComidasPrincipales/sandwich.png"))); // NOI18N
        btnSandwich.setBorder(null);
        btnSandwich.addActionListener(this::btnSandwichActionPerformed);
        jPanel6.add(btnSandwich);

        btnTortillaDePatata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComidasPrincipales/tortilla-espanola.png"))); // NOI18N
        btnTortillaDePatata.setBorder(null);
        btnTortillaDePatata.addActionListener(this::btnTortillaDePatataActionPerformed);
        jPanel6.add(btnTortillaDePatata);

        btnWrap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComidasPrincipales/tortilla.png"))); // NOI18N
        btnWrap.setBorder(null);
        btnWrap.addActionListener(this::btnWrapActionPerformed);
        jPanel6.add(btnWrap);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/volver.png"))); // NOI18N
        btnVolver.addActionListener(this::btnVolverActionPerformed);
        jPanel5.add(btnVolver);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlitasActionPerformed
        seleccionarProducto("Alitas");
    }//GEN-LAST:event_btnAlitasActionPerformed

    private void btnAnillosDeCalamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnillosDeCalamarActionPerformed
        seleccionarProducto("Anillos de calamar");
    }//GEN-LAST:event_btnAnillosDeCalamarActionPerformed

    private void btnCroquetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCroquetasActionPerformed
        seleccionarProducto("Croquetas");
    }//GEN-LAST:event_btnCroquetasActionPerformed

    private void btnChorizoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChorizoActionPerformed
        seleccionarProducto("Chorizo");
    }//GEN-LAST:event_btnChorizoActionPerformed

    private void btnTacosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTacosActionPerformed
         seleccionarProducto("Tacos");
    }//GEN-LAST:event_btnTacosActionPerformed

    private void btnPapasFritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapasFritasActionPerformed
        seleccionarProducto("PapasFritas");
    }//GEN-LAST:event_btnPapasFritasActionPerformed

    private void btnPerroCalienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerroCalienteActionPerformed
        seleccionarProducto("PerroCaliente"); 
    }//GEN-LAST:event_btnPerroCalienteActionPerformed

    private void btnHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaActionPerformed
        seleccionarProducto("Hamburguesa");
    }//GEN-LAST:event_btnHamburguesaActionPerformed

    private void btnBocadilloCalamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBocadilloCalamarActionPerformed
         seleccionarProducto("BocadilloCalamar");
    }//GEN-LAST:event_btnBocadilloCalamarActionPerformed

    private void btnSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSandwichActionPerformed
       seleccionarProducto("Sandwich");
    }//GEN-LAST:event_btnSandwichActionPerformed

    private void btnTortillaDePatataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTortillaDePatataActionPerformed
        seleccionarProducto("TortillaDePatata");
    }//GEN-LAST:event_btnTortillaDePatataActionPerformed

    private void btnWrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWrapActionPerformed
        seleccionarProducto("WrapDePollo");
    }//GEN-LAST:event_btnWrapActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       this.productoSeleccionado = null;
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlitas;
    private javax.swing.JButton btnAnillosDeCalamar;
    private javax.swing.JButton btnBocadilloCalamar;
    private javax.swing.JButton btnChorizo;
    private javax.swing.JButton btnCroquetas;
    private javax.swing.JButton btnHamburguesa;
    private javax.swing.JButton btnPapasFritas;
    private javax.swing.JButton btnPerroCaliente;
    private javax.swing.JButton btnSandwich;
    private javax.swing.JButton btnTacos;
    private javax.swing.JButton btnTortillaDePatata;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnWrap;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelEmpresa1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
