/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author DAM_204
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBebidas = new javax.swing.JButton();
        btnComidas = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        displayOperaciones = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        displayResultado = new javax.swing.JTextArea();
        jPanelBotonesCalculadora = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jButtonSignoDividir = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        jButtonSignoC = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButtonSignoPunto = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        jButtonSignoIgual = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnModo = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnAñadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnEfectivo = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        btnTicket = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayTotales = new javax.swing.JTextArea();
        jPanel14 = new javax.swing.JPanel();
        btnMesa3 = new javax.swing.JButton();
        btnMesa1 = new javax.swing.JButton();
        btnMesa2 = new javax.swing.JButton();
        btnMesa5 = new javax.swing.JButton();
        btnMesa6 = new javax.swing.JButton();
        btnMesa7 = new javax.swing.JButton();
        btnMesa8 = new javax.swing.JButton();
        btnMesa4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnMesero1 = new javax.swing.JButton();
        btnMesero2 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(224, 225, 221));

        jPanel2.setForeground(new java.awt.Color(224, 225, 221));

        jLabelEmpresa.setBackground(new java.awt.Color(142, 202, 230));
        jLabelEmpresa.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabelEmpresa.setForeground(new java.awt.Color(2, 48, 71));
        jLabelEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmpresa.setText("Cafeteria PanRin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
        );

        jPanel3.setForeground(new java.awt.Color(224, 225, 221));
        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 40, 0));

        btnBebidas.setBackground(new java.awt.Color(142, 202, 230));
        btnBebidas.setText("Bebidas");
        btnBebidas.addActionListener(this::btnBebidasActionPerformed);
        jPanel3.add(btnBebidas);

        btnComidas.setBackground(new java.awt.Color(142, 202, 230));
        btnComidas.setForeground(new java.awt.Color(2, 48, 71));
        btnComidas.setText("Comidas");
        btnComidas.setMaximumSize(new java.awt.Dimension(120, 50));
        btnComidas.setMinimumSize(new java.awt.Dimension(120, 50));
        btnComidas.setPreferredSize(new java.awt.Dimension(120, 50));
        jPanel3.add(btnComidas);

        jPanel4.setForeground(new java.awt.Color(224, 225, 221));

        jPanel6.setForeground(new java.awt.Color(224, 225, 221));

        displayOperaciones.setColumns(20);
        displayOperaciones.setFont(new java.awt.Font("Alef", 1, 14)); // NOI18N
        displayOperaciones.setForeground(new java.awt.Color(2, 48, 71));
        displayOperaciones.setRows(5);
        displayOperaciones.setText("display operaiones anteriores\n3+5+8+4\n/2");
        jScrollPane4.setViewportView(displayOperaciones);

        displayResultado.setBackground(new java.awt.Color(255, 224, 147));
        displayResultado.setColumns(20);
        displayResultado.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        displayResultado.setForeground(new java.awt.Color(2, 48, 71));
        displayResultado.setRows(5);
        displayResultado.setText("resultado\n10");
        jScrollPane5.setViewportView(displayResultado);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBotonesCalculadora.setForeground(new java.awt.Color(224, 225, 221));
        jPanelBotonesCalculadora.setLayout(new java.awt.GridLayout(5, 4));

        btn7.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn7.setText("7");
        btn7.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn7);

        btn8.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn8.setText("8");
        btn8.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn8);

        btn9.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn9.setText("9");
        btn9.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn9);

        jButtonSignoDividir.setBackground(new java.awt.Color(142, 202, 230));
        jButtonSignoDividir.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        jButtonSignoDividir.setText("/");
        jButtonSignoDividir.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(jButtonSignoDividir);

        btn4.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn4.setText("4");
        btn4.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn4);

        btn5.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn5.setText("5");
        btn5.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn5);

        btn6.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn6.setText("6");
        btn6.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn6);

        btnMult.setBackground(new java.awt.Color(142, 202, 230));
        btnMult.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btnMult.setText("x");
        btnMult.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btnMult);

        btn1.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn1.setText("1");
        btn1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn1);

        btn2.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn2.setText("2");
        btn2.setMargin(new java.awt.Insets(1, 1, 1, 1));
        btn2.addActionListener(this::btn2ActionPerformed);
        jPanelBotonesCalculadora.add(btn2);

        btn3.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn3.setText("3");
        btn3.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn3);

        btnResta.setBackground(new java.awt.Color(142, 202, 230));
        btnResta.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btnResta.setText("-");
        btnResta.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btnResta);

        jButtonSignoC.setBackground(new java.awt.Color(251, 133, 0));
        jButtonSignoC.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        jButtonSignoC.setForeground(new java.awt.Color(2, 48, 71));
        jButtonSignoC.setText("C");
        jButtonSignoC.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jButtonSignoC.addActionListener(this::jButtonSignoCActionPerformed);
        jPanelBotonesCalculadora.add(jButtonSignoC);

        btn0.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btn0.setText("0");
        btn0.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btn0);

        jButtonSignoPunto.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        jButtonSignoPunto.setText(".");
        jButtonSignoPunto.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(jButtonSignoPunto);

        btnSuma.setBackground(new java.awt.Color(142, 202, 230));
        btnSuma.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        btnSuma.setText("+");
        btnSuma.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(btnSuma);

        jButtonSignoIgual.setFont(new java.awt.Font("Alef", 1, 20)); // NOI18N
        jButtonSignoIgual.setText("=");
        jButtonSignoIgual.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanelBotonesCalculadora.add(jButtonSignoIgual);

        jPanel12.setForeground(new java.awt.Color(224, 225, 221));
        jPanel12.setLayout(new java.awt.GridLayout(4, 0));

        jPanel7.setForeground(new java.awt.Color(224, 225, 221));
        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        btnModo.setBackground(new java.awt.Color(33, 158, 188));
        btnModo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModo.setText("Modo Calculadora");
        jPanel7.add(btnModo);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        btnAñadir.setBackground(new java.awt.Color(33, 158, 188));
        btnAñadir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAñadir.setText("Añadir Producto");
        btnAñadir.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jPanel13.add(btnAñadir);

        btnBorrar.setBackground(new java.awt.Color(251, 133, 0));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar Seleccion");
        btnBorrar.addActionListener(this::btnBorrarActionPerformed);
        jPanel13.add(btnBorrar);

        jPanel7.add(jPanel13);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelBotonesCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanelBotonesCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setForeground(new java.awt.Color(224, 225, 221));

        jPanel11.setForeground(new java.awt.Color(224, 225, 221));
        jPanel11.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        btnEfectivo.setBackground(new java.awt.Color(33, 158, 188));
        btnEfectivo.setText("Efectivo");
        btnEfectivo.addActionListener(this::btnEfectivoActionPerformed);
        jPanel11.add(btnEfectivo);

        btnTarjeta.setBackground(new java.awt.Color(33, 158, 188));
        btnTarjeta.setText("Tarjeta");
        jPanel11.add(btnTarjeta);

        btnTicket.setBackground(new java.awt.Color(142, 202, 230));
        btnTicket.setText("Ticket");
        btnTicket.addActionListener(this::btnTicketActionPerformed);
        jPanel11.add(btnTicket);

        btnFactura.setBackground(new java.awt.Color(142, 202, 230));
        btnFactura.setText("Factura");
        jPanel11.add(btnFactura);

        jPanel15.setForeground(new java.awt.Color(224, 225, 221));

        tablaProductos.setBackground(new java.awt.Color(2, 48, 71));
        tablaProductos.setForeground(new java.awt.Color(255, 255, 255));
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        jPanel8.setForeground(new java.awt.Color(224, 225, 221));

        displayTotales.setBackground(new java.awt.Color(255, 221, 151));
        displayTotales.setColumns(20);
        displayTotales.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        displayTotales.setForeground(new java.awt.Color(2, 48, 71));
        displayTotales.setRows(5);
        displayTotales.setText("|   SUBTOTAL:      9.00 €    \n                                    \n│  IVA (21%):     1.89 €        CANTIDAD: [  1  ]               \n│  ─────────────────────       \n│  TOTAL:        10.89 €  ");
        jScrollPane3.setViewportView(displayTotales);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel14.setForeground(new java.awt.Color(224, 225, 221));

        btnMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa3.png"))); // NOI18N
        btnMesa3.setBorder(null);
        btnMesa3.setBorderPainted(false);
        btnMesa3.setContentAreaFilled(false);
        btnMesa3.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa3.setPreferredSize(new java.awt.Dimension(60, 60));

        btnMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa1.png"))); // NOI18N
        btnMesa1.setBorder(null);
        btnMesa1.setBorderPainted(false);
        btnMesa1.setContentAreaFilled(false);
        btnMesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa2.png"))); // NOI18N
        btnMesa2.setBorder(null);
        btnMesa2.setBorderPainted(false);
        btnMesa2.setContentAreaFilled(false);
        btnMesa2.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa2.setPreferredSize(new java.awt.Dimension(60, 60));

        btnMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa5.png"))); // NOI18N
        btnMesa5.setBorder(null);
        btnMesa5.setBorderPainted(false);
        btnMesa5.setContentAreaFilled(false);
        btnMesa5.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa5.setPreferredSize(new java.awt.Dimension(60, 60));

        btnMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa6.png"))); // NOI18N
        btnMesa6.setBorder(null);
        btnMesa6.setBorderPainted(false);
        btnMesa6.setContentAreaFilled(false);
        btnMesa6.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa6.setPreferredSize(new java.awt.Dimension(60, 60));
        btnMesa6.addActionListener(this::btnMesa6ActionPerformed);

        btnMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa7.png"))); // NOI18N
        btnMesa7.setBorder(null);
        btnMesa7.setBorderPainted(false);
        btnMesa7.setContentAreaFilled(false);
        btnMesa7.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa7.setPreferredSize(new java.awt.Dimension(60, 60));

        btnMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa8.png"))); // NOI18N
        btnMesa8.setBorder(null);
        btnMesa8.setBorderPainted(false);
        btnMesa8.setContentAreaFilled(false);
        btnMesa8.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa8.setPreferredSize(new java.awt.Dimension(60, 60));
        btnMesa8.addActionListener(this::btnMesa8ActionPerformed);

        btnMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mesa4.png"))); // NOI18N
        btnMesa4.setBorder(null);
        btnMesa4.setBorderPainted(false);
        btnMesa4.setContentAreaFilled(false);
        btnMesa4.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        btnMesa4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnMesa4.setPreferredSize(new java.awt.Dimension(60, 60));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesa6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMesa7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setForeground(new java.awt.Color(224, 225, 221));
        jPanel9.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        btnMesero1.setBackground(new java.awt.Color(33, 158, 188));
        btnMesero1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMesero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camarera.png"))); // NOI18N
        btnMesero1.setText("Mesero1");
        jPanel9.add(btnMesero1);

        btnMesero2.setBackground(new java.awt.Color(33, 158, 188));
        btnMesero2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnMesero2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/camarero.png"))); // NOI18N
        btnMesero2.setText("Mesero2");
        jPanel9.add(btnMesero2);

        jPanel16.setForeground(new java.awt.Color(224, 225, 221));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTicketActionPerformed

    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEfectivoActionPerformed

    private void btnMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesa6ActionPerformed

    private void btnMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesa8ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void jButtonSignoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSignoCActionPerformed

    private void btnBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBebidasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBebidasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnBebidas;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnComidas;
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnMesa1;
    private javax.swing.JButton btnMesa2;
    private javax.swing.JButton btnMesa3;
    private javax.swing.JButton btnMesa4;
    private javax.swing.JButton btnMesa5;
    private javax.swing.JButton btnMesa6;
    private javax.swing.JButton btnMesa7;
    private javax.swing.JButton btnMesa8;
    private javax.swing.JButton btnMesero1;
    private javax.swing.JButton btnMesero2;
    private javax.swing.JButton btnModo;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JButton btnTicket;
    private javax.swing.JTextArea displayOperaciones;
    private javax.swing.JTextArea displayResultado;
    private javax.swing.JTextArea displayTotales;
    private javax.swing.JButton jButtonSignoC;
    private javax.swing.JButton jButtonSignoDividir;
    private javax.swing.JButton jButtonSignoIgual;
    private javax.swing.JButton jButtonSignoPunto;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBotonesCalculadora;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
