/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author DAM_204
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelEmpresa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonBebidas = new javax.swing.JButton();
        jButtonComida = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelBotonesCalculadora = new javax.swing.JPanel();
        jButtonSignoC = new javax.swing.JButton();
        jButtonSignoCambioMasMenos = new javax.swing.JButton();
        jButtonSignoPorcentaje = new javax.swing.JButton();
        jButtonSignoDividir = new javax.swing.JButton();
        jButtonNumero7 = new javax.swing.JButton();
        jButtonNumero8 = new javax.swing.JButton();
        jButtonNumero9 = new javax.swing.JButton();
        jButtonSignoMultiplicacion = new javax.swing.JButton();
        jButtonNumero4 = new javax.swing.JButton();
        jButtonnumero5 = new javax.swing.JButton();
        jButtonNumero6 = new javax.swing.JButton();
        jButtonSignoMenos = new javax.swing.JButton();
        jButtonNumero1 = new javax.swing.JButton();
        jButtonNumero2 = new javax.swing.JButton();
        jButtonNumero3 = new javax.swing.JButton();
        jButtonSignoMas = new javax.swing.JButton();
        jButtonNumero0 = new javax.swing.JButton();
        jButtonSignoPunto = new javax.swing.JButton();
        jButtonSignoIgual = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonCalculadora = new javax.swing.JButton();
        jButtonCantidad = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTablePantallaPrincipal = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButtonAñadir = new javax.swing.JButton();
        jButtoBorrar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButtonEfectivo = new javax.swing.JButton();
        jButtonTarjeta = new javax.swing.JButton();
        jButtonTicket = new javax.swing.JButton();
        jButtonFactura = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButtonAdministrador = new javax.swing.JButton();
        jButtonMesero1 = new javax.swing.JButton();
        jButtonMesero2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelEmpresa.setText("Cafeteria PanRin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setLayout(new java.awt.GridLayout(1, 4, 40, 0));

        jButtonBebidas.setText("Bebidas");
        jPanel3.add(jButtonBebidas);

        jButtonComida.setText("Comidas");
        jPanel3.add(jButtonComida);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBotonesCalculadora.setLayout(new java.awt.GridLayout(5, 4));

        jButtonSignoC.setText("C");
        jButtonSignoC.addActionListener(this::jButtonSignoCActionPerformed);
        jPanelBotonesCalculadora.add(jButtonSignoC);

        jButtonSignoCambioMasMenos.setText("±");
        jPanelBotonesCalculadora.add(jButtonSignoCambioMasMenos);

        jButtonSignoPorcentaje.setText("%");
        jPanelBotonesCalculadora.add(jButtonSignoPorcentaje);

        jButtonSignoDividir.setText("/");
        jPanelBotonesCalculadora.add(jButtonSignoDividir);

        jButtonNumero7.setText("7");
        jPanelBotonesCalculadora.add(jButtonNumero7);

        jButtonNumero8.setText("8");
        jPanelBotonesCalculadora.add(jButtonNumero8);

        jButtonNumero9.setText("9");
        jPanelBotonesCalculadora.add(jButtonNumero9);

        jButtonSignoMultiplicacion.setText("x");
        jPanelBotonesCalculadora.add(jButtonSignoMultiplicacion);

        jButtonNumero4.setText("4");
        jPanelBotonesCalculadora.add(jButtonNumero4);

        jButtonnumero5.setText("5");
        jPanelBotonesCalculadora.add(jButtonnumero5);

        jButtonNumero6.setText("6");
        jPanelBotonesCalculadora.add(jButtonNumero6);

        jButtonSignoMenos.setText("-");
        jPanelBotonesCalculadora.add(jButtonSignoMenos);

        jButtonNumero1.setText("1");
        jPanelBotonesCalculadora.add(jButtonNumero1);

        jButtonNumero2.setText("2");
        jButtonNumero2.addActionListener(this::jButtonNumero2ActionPerformed);
        jPanelBotonesCalculadora.add(jButtonNumero2);

        jButtonNumero3.setText("3");
        jPanelBotonesCalculadora.add(jButtonNumero3);

        jButtonSignoMas.setText("+");
        jPanelBotonesCalculadora.add(jButtonSignoMas);

        jButtonNumero0.setText("0");
        jPanelBotonesCalculadora.add(jButtonNumero0);

        jButtonSignoPunto.setText(".");
        jPanelBotonesCalculadora.add(jButtonSignoPunto);

        jButtonSignoIgual.setText("=");
        jPanelBotonesCalculadora.add(jButtonSignoIgual);

        jPanel12.setLayout(new java.awt.GridLayout(4, 0));

        jPanel7.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jButtonCalculadora.setText("Calculadora");
        jPanel7.add(jButtonCalculadora);

        jButtonCantidad.setText("Cantidad");
        jPanel7.add(jButtonCantidad);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBotonesCalculadora, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonesCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        JTablePantallaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(JTablePantallaPrincipal);

        jPanel10.setLayout(new java.awt.GridLayout(1, 5, 40, 10));

        jButtonAñadir.setText("Añadir Producto");
        jPanel10.add(jButtonAñadir);

        jButtoBorrar.setText("Borrar Producto");
        jPanel10.add(jButtoBorrar);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jButtonEfectivo.setText("Efectivo");
        jButtonEfectivo.addActionListener(this::jButtonEfectivoActionPerformed);
        jPanel11.add(jButtonEfectivo);

        jButtonTarjeta.setText("Tarjeta");
        jPanel11.add(jButtonTarjeta);

        jButtonTicket.setText("Ticket");
        jButtonTicket.addActionListener(this::jButtonTicketActionPerformed);
        jPanel11.add(jButtonTicket);

        jButtonFactura.setText("Factura");
        jPanel11.add(jButtonFactura);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jPanel9.setLayout(new java.awt.GridLayout(1, 3));

        jButtonAdministrador.setText("Administrador");
        jPanel9.add(jButtonAdministrador);

        jButtonMesero1.setText("Mesero1");
        jPanel9.add(jButtonMesero1);

        jButtonMesero2.setText("Mesero2");
        jPanel9.add(jButtonMesero2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSignoCActionPerformed

    private void jButtonNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNumero2ActionPerformed

    private void jButtonEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEfectivoActionPerformed

    private void jButtonTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTicketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablePantallaPrincipal;
    private javax.swing.JButton jButtoBorrar;
    private javax.swing.JButton jButtonAdministrador;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonBebidas;
    private javax.swing.JButton jButtonCalculadora;
    private javax.swing.JButton jButtonCantidad;
    private javax.swing.JButton jButtonComida;
    private javax.swing.JButton jButtonEfectivo;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonMesero1;
    private javax.swing.JButton jButtonMesero2;
    private javax.swing.JButton jButtonNumero0;
    private javax.swing.JButton jButtonNumero1;
    private javax.swing.JButton jButtonNumero2;
    private javax.swing.JButton jButtonNumero3;
    private javax.swing.JButton jButtonNumero4;
    private javax.swing.JButton jButtonNumero6;
    private javax.swing.JButton jButtonNumero7;
    private javax.swing.JButton jButtonNumero8;
    private javax.swing.JButton jButtonNumero9;
    private javax.swing.JButton jButtonSignoC;
    private javax.swing.JButton jButtonSignoCambioMasMenos;
    private javax.swing.JButton jButtonSignoDividir;
    private javax.swing.JButton jButtonSignoIgual;
    private javax.swing.JButton jButtonSignoMas;
    private javax.swing.JButton jButtonSignoMenos;
    private javax.swing.JButton jButtonSignoMultiplicacion;
    private javax.swing.JButton jButtonSignoPorcentaje;
    private javax.swing.JButton jButtonSignoPunto;
    private javax.swing.JButton jButtonTarjeta;
    private javax.swing.JButton jButtonTicket;
    private javax.swing.JButton jButtonnumero5;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBotonesCalculadora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
