/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author DAM_202
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxProcesador = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonLinux = new javax.swing.JRadioButton();
        jRadioButtonWindows = new javax.swing.JRadioButton();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jCheckRam = new javax.swing.JCheckBox();
        jCheckSSD = new javax.swing.JCheckBox();
        jCheckWifi = new javax.swing.JCheckBox();
        jCheckTarjetaGrafica = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSliderMonitores = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPerifericos = new javax.swing.JList<>();
        jButtonTotal = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(237, 242, 244));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 72, 69));
        jLabel1.setText("Procesador");

        jComboBoxProcesador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBoxProcesador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "• Intel i3", "• Intel i5", "• Intel i7", "• Ryzen 5", "• Ryzen 7" }));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 72, 69));
        jLabel2.setText("Sistema Operativo");

        buttonGroup1.add(jRadioButtonLinux);
        jRadioButtonLinux.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButtonLinux.setForeground(new java.awt.Color(78, 72, 69));
        jRadioButtonLinux.setText("Linux");

        buttonGroup1.add(jRadioButtonWindows);
        jRadioButtonWindows.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButtonWindows.setForeground(new java.awt.Color(78, 72, 69));
        jRadioButtonWindows.setText("Windows");

        buttonGroup1.add(jRadioButtonNinguno);
        jRadioButtonNinguno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButtonNinguno.setForeground(new java.awt.Color(78, 72, 69));
        jRadioButtonNinguno.setText("Ninguno");
        jRadioButtonNinguno.addActionListener(this::jRadioButtonNingunoActionPerformed);

        jCheckRam.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckRam.setForeground(new java.awt.Color(78, 72, 69));
        jCheckRam.setText("16 Ram");
        jCheckRam.addActionListener(this::jCheckRamActionPerformed);

        jCheckSSD.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckSSD.setForeground(new java.awt.Color(78, 72, 69));
        jCheckSSD.setText("SSD 1T");

        jCheckWifi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckWifi.setForeground(new java.awt.Color(78, 72, 69));
        jCheckWifi.setText("Wifi");

        jCheckTarjetaGrafica.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckTarjetaGrafica.setForeground(new java.awt.Color(78, 72, 69));
        jCheckTarjetaGrafica.setText("Tarjeta Gráfica");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 72, 69));
        jLabel3.setText("Componentes");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 72, 69));
        jLabel4.setText("Monitores");

        jSliderMonitores.setMajorTickSpacing(1);
        jSliderMonitores.setMaximum(4);
        jSliderMonitores.setMinimum(1);
        jSliderMonitores.setMinorTickSpacing(1);
        jSliderMonitores.setPaintLabels(true);
        jSliderMonitores.setPaintTicks(true);
        jSliderMonitores.setSnapToTicks(true);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 72, 69));
        jLabel5.setText("Periféricos");

        jListPerifericos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "• Teclado", "• Ratón \t", "• Auriculares \t", "• Webcam \t", "• Altavoces \t" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPerifericos);

        jButtonTotal.setBackground(new java.awt.Color(204, 255, 204));
        jButtonTotal.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(this::jButtonTotalActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSliderMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(37, 37, 37)
                                .addComponent(jRadioButtonLinux)
                                .addGap(30, 30, 30)
                                .addComponent(jRadioButtonWindows))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckRam)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckSSD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckWifi)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckTarjetaGrafica))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jRadioButtonNinguno)))
                        .addGap(0, 39, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxProcesador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonLinux)
                    .addComponent(jRadioButtonWindows)
                    .addComponent(jRadioButtonNinguno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckRam)
                    .addComponent(jCheckSSD)
                    .addComponent(jCheckWifi)
                    .addComponent(jCheckTarjetaGrafica))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButtonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNingunoActionPerformed

    private void jCheckRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckRamActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        int precio=0;
        String procesador =  jComboBoxProcesador.getSelectedItem().toString();
        String procesadorSeleccionado=null;        
        if (procesador.contains("Intel i3")){
            precio +=100;
            procesadorSeleccionado="Intel i3";            
        }else if (procesador.contains("Intel i5")){
            precio +=180;
            procesadorSeleccionado="Intel i5";            
        }else if (procesador.contains("Intel i7")){
            precio +=280;
            procesadorSeleccionado="Intel i7";            
        }else if (procesador.contains("Ryzen 5")){
            precio +=160;
            procesadorSeleccionado="Ryzen 5";            
        }else if (procesador.contains("Ryzen 7")){
            precio +=260;
            procesadorSeleccionado="Ryzen 7";
        }
        
        String so= buttonGroup1.getSelection().toString();
        String  sistemaSeleccionado=null;        
        if (jRadioButtonLinux.isSelected()){
            sistemaSeleccionado= "Linux";
            
        }else if (jRadioButtonWindows.isSelected()){
            sistemaSeleccionado= "Windows";
            precio +=100;
        }else if (jRadioButtonNinguno.isSelected()){
            sistemaSeleccionado= "sistema Operativo no seleccionado";
        } 
        
        
        
       List<String> componentesSeleccionados=new ArrayList<>();
       if(jCheckRam.isSelected()){
            precio+=40;
            componentesSeleccionados.add("16 GB RAM");
        }
        if(jCheckSSD.isSelected()){
            precio+=70;
            componentesSeleccionados.add("SSD 1TB");
        }
        if(jCheckWifi.isSelected()){
            precio+=20;
            componentesSeleccionados.add("Wifi");
        }
        if(jCheckTarjetaGrafica.isSelected()){
            precio+=150;
            componentesSeleccionados.add("Targeta Gráfica");
        }
        
        int cantidadMonitor= jSliderMonitores.getValue();
        precio +=cantidadMonitor*120;
        
        
        List<String> perifericosSeleccionados= new ArrayList<>();
        List<String> seleccionLista = jListPerifericos.getSelectedValuesList();
        
        
        for (String periferico : seleccionLista) {
        if (periferico.contains("Teclado")) {
            precio += 20;
            perifericosSeleccionados.add("Teclado");
        }
        if (periferico.contains("Ratón")) {
            precio += 15;
            perifericosSeleccionados.add("Ratón");
        }
        if (periferico.contains("Auriculares")) {
            precio += 30;
            perifericosSeleccionados.add("Auriculares");
        }
        if (periferico.contains("Webcam")) {
            precio += 25;
            perifericosSeleccionados.add("Webcam");
        }
        if (periferico.contains("Altavoces")) {
            precio += 40;
            perifericosSeleccionados.add("Altavoces");
        }
        
        
        
        
        
       
       
       JOptionPane.showMessageDialog(this, 
        "========== CONFIGURACIÓN ==========\n" +
        "Procesador: " + procesadorSeleccionado + "\n" +
        "Sistema Operativo: " + sistemaSeleccionado + "\n\n" +
        "Componentes:\n" + componentesSeleccionados + "\n\n" +
        "Monitores: " + cantidadMonitor + "\n\n" +
        "Periféricos:\n" + perifericosSeleccionados + "\n" +
        "========================================\n" +
        "Precio final: " + precio + "€\n" +
        "========================================"
    );
        
    }       

    }//GEN-LAST:event_jButtonTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JCheckBox jCheckRam;
    private javax.swing.JCheckBox jCheckSSD;
    private javax.swing.JCheckBox jCheckTarjetaGrafica;
    private javax.swing.JCheckBox jCheckWifi;
    private javax.swing.JComboBox<String> jComboBoxProcesador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListPerifericos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonLinux;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JRadioButton jRadioButtonWindows;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderMonitores;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
